# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Build Hugo

jobs:
  blogdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R packages
        run: |
          install.packages(c("rmarkdown", "blogdown"))
        shell: Rscript {0}

      - name: Install hugo
        run: R -e 'blogdown::install_hugo(extended = TRUE, version = "0.81.0")'

      - name: Build site
        run: R -e 'if (!blogdown::hugo_build()==0) stop("Hugo build failed.")'

      # Install Netlify CLI
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install -g netlify-cli

      # Preview deploys for PRs
      - name: Deploy preview to Netlify
        if: github.event_name == 'pull_request'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --dir=public

      # Production deploys on pushes to main/master
      - name: Deploy production to Netlify
        if: github.event_name != 'pull_request'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir=public
